CREATE TABLE IF NOT EXISTS NOTE (
    ID UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    TITLE VARCHAR(250) CHECK(LENGTH(TITLE)>=3 AND LENGTH(TITLE)<=250) NOT NULL,
    CONTENT VARCHAR NOT NULL,
    LAST_UPDATED_DATE DATE NOT NULL,
    CREATED_DATE DATE NOT NULL
    );